# Generated by Django 2.2 on 2020-01-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_stranger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
